### ISSUE TITLE
YALMA doesn't return the visits anymore.

### ISSUE THREAD

**Issue by BeniaminK** [m-grzesiak/yalma#25]
Hi, yalma stopped reporting new visits recently.

Could you provide some information of how do you track the packages on Android so that I might update the Luxmed API?

**Comment by m-grzesiak** [comment]
@BeniaminK are you sure? I've just tested every scenario and it works like a charm. Do you have the newest code?

**Comment by BeniaminK** [comment]
The newest code works good, thank you!
