### ISSUE TITLE
Niestety przestalo dzialac :( 

### ISSUE THREAD

**Issue by maciej1988** [m-grzesiak/yalma#26]
C:\Users\Maciek\Desktop\python luxmed\yalma-master\yalma-master>python yalma.py monitor --email xxxxxx@gmail.com --city-id 3 --service-id 6621 --to-date 2023-11-08
Getting terms for given search parameters...
Traceback (most recent call last):
  File "yalma.py", line 91, in <module>
    main()
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "yalma.py", line 72, in monitor
    available_terms = booking_service.get_available_terms(city_id, service_id, parsed_from_date, parsed_to_date,
  File "C:\Users\Maciek\Desktop\python luxmed\yalma-master\yalma-master\booking_service.py", line 45, in get_available_terms
    result = luxmed_api.get_terms(city_id, service_id, from_date, to_date, language, clinic_id, doctor_id)
  File "C:\Users\Maciek\Desktop\python luxmed\yalma-master\yalma-master\luxmed_api.py", line 67, in get_terms
    __validate_response(response)
  File "C:\Users\Maciek\Desktop\python luxmed\yalma-master\yalma-master\luxmed_api.py", line 139, in __validate_response
    raise LuxmedApiException("Something went wrong")
luxmed_api.LuxmedApiException: Something went wrong

**Comment by 0lfu** [comment]
trzeba dodać parametr "delocalized": "true" w get_terms

**Comment by m-grzesiak** [comment]
@maciej1988 @olfu79 Przyjrzę się temu w tym tygodniu, jak będę miał czas i opublikuję fixa ;)

**Comment by pawgoz** [comment]
Faktycznie dodanie parametru delocalized": "true" w get_terms na jakiś czas pomogło, ale najwyraźniej znowu coś się zmieniło w api, bo znowu:
`Traceback (most recent call last):
  File "/home/pawel/projekt/luxmed/yalma/yalma.py", line 97, in <module>
    main()
  File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pawel/projekt/luxmed/yalma/yalma.py", line 78, in monitor
    available_terms = booking_service.get_available_terms(city_id, service_id, parsed_from_date, parsed_to_date,
  File "/home/pawel/projekt/luxmed/yalma/booking_service.py", line 45, in get_available_terms
    result = luxmed_api.get_terms(city_id, service_id, from_date, to_date, language, clinic_id, doctor_id)
  File "/home/pawel/projekt/luxmed/yalma/luxmed_api.py", line 68, in get_terms
    __validate_response(response)
  File "/home/pawel/projekt/luxmed/yalma/luxmed_api.py", line 140, in __validate_response
    raise LuxmedApiException("Something went wrong")
luxmed_api.LuxmedApiException: Something went wrong
`

**Comment by 0lfu** [comment]
> Faktycznie dodanie parametru delocalized": "true" w get_terms na jakiś czas pomogło, ale najwyraźniej znowu coś się zmieniło w api, bo znowu: `Traceback (most recent call last): File "/home/pawel/projekt/luxmed/yalma/yalma.py", line 97, in <module> main() File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 829, in __call__ return self.main(*args, **kwargs) File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 782, in main rv = self.invoke(ctx) File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) File "/home/pawel/projekt/luxmed/yalma/yalma.py", line 78, in monitor available_terms = booking_service.get_available_terms(city_id, service_id, parsed_from_date, parsed_to_date, File "/home/pawel/projekt/luxmed/yalma/booking_service.py", line 45, in get_available_terms result = luxmed_api.get_terms(city_id, service_id, from_date, to_date, language, clinic_id, doctor_id) File "/home/pawel/projekt/luxmed/yalma/luxmed_api.py", line 68, in get_terms __validate_response(response) File "/home/pawel/projekt/luxmed/yalma/luxmed_api.py", line 140, in __validate_response raise LuxmedApiException("Something went wrong") luxmed_api.LuxmedApiException: Something went wrong `

należy zmienić na nowszą wersję aplikacji - "4.29.0"

**Comment by pawgoz** [comment]
> > Faktycznie dodanie parametru delocalized": "true" w get_terms na jakiś czas pomogło, ale najwyraźniej znowu coś się zmieniło w api, bo znowu: `Traceback (most recent call last): File "/home/pawel/projekt/luxmed/yalma/yalma.py", line 97, in <module> main() File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 829, in __call__ return self.main(*args, **kwargs) File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 782, in main rv = self.invoke(ctx) File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/pawel/projekt/luxmed/lux/lib/python3.10/site-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) File "/home/pawel/projekt/luxmed/yalma/yalma.py", line 78, in monitor available_terms = booking_service.get_available_terms(city_id, service_id, parsed_from_date, parsed_to_date, File "/home/pawel/projekt/luxmed/yalma/booking_service.py", line 45, in get_available_terms result = luxmed_api.get_terms(city_id, service_id, from_date, to_date, language, clinic_id, doctor_id) File "/home/pawel/projekt/luxmed/yalma/luxmed_api.py", line 68, in get_terms __validate_response(response) File "/home/pawel/projekt/luxmed/yalma/luxmed_api.py", line 140, in __validate_response raise LuxmedApiException("Something went wrong") luxmed_api.LuxmedApiException: Something went wrong `
> 
> należy zmienić na nowszą wersję aplikacji - "4.29.0"

Mam zmienioną. Jeżeli jest zła wersja, to w odpowiedzi dostajemy:
`
luxmed_api.LuxmedApiException: {'Errors': [{'ErrorCode': 301, 'Message': 'The currently installed version of the application is not supported by the new Patient Portal system. Please update the application to the latest version to use it.', 'AdditionalData': {'ShopUrl': 'market://details?id=pl.luxmed.pp', 'FallbackUrl': 'http://play.google.com/store/apps/details?id=pl.luxmed.pp', 'Title': 'Update the application'}}]}
`

**Comment by m-grzesiak** [comment]
@0lfu to nie pomoże, sam teraz sprawdzałem ;)

@pawgoz ja muszę siąść nad tym kompleksowo. Niestety od czasu, gdy Luxmed ma całkowicie inny UI, zmienili API na "pseudo-restowe". Taki problem niestety wymaga konkretnego działania i wzięcia aplikacji na warsztat. Problemem z Luxmedowym API jest to, że jak się nie wstrzelisz we flow, które zakłada API, przy requeście co najwyżej dostaniesz w odpowiedzi stronę logowania w HTMLu (i w takim przypadku rzucam właśnie generyczny exception z wiadomością "something went wrong", bo to są przypadki, których niestety nie idzie zdebugować ;) 

Muszę znaleźć chwilę i zobaczyć, co się znowu zmieniło w tym API przez ostatni rok, ale to nie jest łatwe zadanie. Może znajdę czas w ten weekend (co nie znaczy, że znajdę w tym czasie rozwiązanie  problemu ;)). Rok temu musiałem przepisać obsługę całego API, żeby to wszystko z powrotem zabanglało - nie wiadomo, czy znowu tak nie będzie.

**Comment by m-grzesiak** [comment]
@pawgoz jakby co, to [wystawiłem pull request](https://github.com/m-grzesiak/yalma/pull/27) - błąd już nie występuje, nie testowałem jednak poprawności parsowania odpowiedzi. Jeśli chcesz, możesz sprawdzić, czy działa ;) Ja siądę sobie do tego w weekend

**Comment by m-grzesiak** [comment]
@maciej1988 @pawgoz przetestowałem. Wszystko działa. Zaciągnijcie najnowsze zmiany z mastera i potwierdźcie proszę, że nie macie problemu ;)

**Comment by pawgoz** [comment]
@m-grzesiak przetestowałem i działa jak należy ;) dzięki
