### ISSUE TITLE
Problem z aplikacją

### ISSUE THREAD

**Issue by daro997** [m-grzesiak/yalma#28]
Spróbowałem dziś pierwszy raz odpalić aplikację, zainstalowałem biblioteki, nie konfigurowałem ustawień SMTP. Przy pr obie uruchomienia dostaję:

/luxmed/yalma-master$ python yalma.py cities
  File "yalma.py", line 77
    def __display_results(results: {}, headers: [str]):
                                 ^
SyntaxError: invalid syntax

Mam pythona w wersji 2.7.16. Mo ze za stary?

**Comment by daro997** [comment]
Ok, widzę  ze python3 (3.9.2) działa.

**Comment by daro997** [comment]
Mam dwa pytania: w jaki sposób można podać dwie lokalizacje w których ma nastąpić wyszukiwanie?
Mam wrażenie że są różne numery usług w zależności od tego czy ma się skierowanie do lekarza czy nie. Mozna to jakoś uwzględnić w aplikacji? Sprawdzałem akurat na rehabilitację która ma inny numer usługi niż 6

**Comment by m-grzesiak** [comment]
AD1 - po prostu wołaj w CRONie 2x aplikację z podanymi w różny sposób parametrami.
AD2 - to jest prezentowanie tego, co luxmed udostępnia po API, więc niestety na takie rzeczy nie mam wpływu ;(
